specs/alpha: Ship sys-fs/dmraid on the livecd
Expected to fix the livecd build which is currently failing with

   Error: --dmraid requires sys-fs/dmraid
          to be installed on the host system.